# -*- coding: utf-8 -*-
"""Fashion_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk0BJlKuN5d2KqUSkBx73wkYr_MtbnxG
"""

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np
import matplotlib.pyplot as plt

# 1. Load the Fashion MNIST dataset
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

# Reshape for the CNN (adding the color channel)
train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

# 2. Build the 6-Layer CNN
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)), # Layer 1
    layers.MaxPooling2D((2, 2)),                                         # Layer 2
    layers.Conv2D(64, (3, 3), activation='relu'),                        # Layer 3
    layers.Flatten(),                                                    # Layer 4
    layers.Dense(64, activation='relu'),                                 # Layer 5
    layers.Dense(10, activation='softmax')                               # Layer 6
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# 3. Train the model
model.fit(train_images, train_labels, epochs=5)

# 4. Make Predictions
# Let's predict the first two images of the test set
predictions = model.predict(test_images[:2])
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

for i in range(2):
    predicted_label = np.argmax(predictions[i])
    actual_label = test_labels[i]
    print(f"Image {i+1}: Predicted: {class_names[predicted_label]}, Actual: {class_names[actual_label]}")